PurBeurre/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from substitut import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^substitut/', include('substitut.urls', namespace='substitut')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

substitut/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from . import views  # import views so we can use them in urls.

app_name = 'substitut'

urlpatterns = [
    url(r'^(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^search', views.search, name='search'),
    url(r'^mentionslegales/$', views.mentionslegales, name='mentionslegales'),
    url(r'^useraccount/$', views.useraccount, name='useraccount'),
    url(r'^userproducts/$', views.userproducts, name='userproducts'),
    url(r'^products/$', views.products, name='products'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', LoginView.as_view(template_name='substitut/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='substitut/logout.html'), name='logout'),
]

substitut/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Users(models.Model):
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=20)

    def __str__(self):
        return str(self.email)


class Products(models.Model):
    name = models.CharField(max_length=100)
    nutriscore = models.CharField(max_length=1)
    category = ArrayField(models.CharField(max_length=900), size=1, default=list, null=True)
    picture = models.URLField()
    url = models.URLField()

    def __str__(self):
        return self.name


class Saving(models.Model):
    contact = models.CharField(max_length=100, default='')
    product_key = models.CharField(max_length=9000, default='')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.contact)

    class Meta:
        ordering = ['date']

substitut/views.py
import json
import requests

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

from .form import Connexion
from .models import Products, Users, Saving
from .pagination import customizePagination


# Create your views here.
def index(request):
    """Return Index page"""
    return render(request, 'substitut/index.html')


def signup(request):
    """Signup function for user"""
    error = False

    if request.method == "POST":
        form = Connexion(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            if email and password:
                user = User.objects.create_user(username=username,
                                                email=email,
                                                password=password)
                user.save()
                users_db = Users.objects.create(email=email,
                                                password=password)
                users_db.save()
                user = authenticate(username=username,
                                    email=email,
                                    password=password)
                login(request, user)
            else:
                error = True
    else:
        form = Connexion()

    return render(request, 'substitut/signup.html', locals())


def userlogin(request):
    """LogIn a registered user"""
    error = False

    if request.method == "POST":
        form = Connexion(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username,
                                email=email,
                                password=password)
            login(request, user)
        else:
            error = True

    else:
        form = Connexion()

    return render(request, 'substitut/login.html', locals())


def userlogout(request):
    """Logout a registered user"""
    logout(request)
    return render(request, 'substitut/logout.html', locals())


def mentionslegales(request):
    """Return Mentions légales page"""
    return render(request, 'substitut/mentionslegales.html')


def useraccount(request):
    """Return User account page"""
    user_data = Users.objects.all()
    context = {"user_data": user_data}
    return render(request, 'substitut/useraccount.html', context)


def products(request):
    """Return all products"""
    product = Products.objects.all()
    context = {"product": product}
    return render(request, 'substitut/products.html', context)


def userproducts(request):
    """Return saved products of a user"""
    try:
        user = request.user.email
        products_to_display = Saving.objects.filter(contact=user)
        keys_list = []

        for item in products_to_display:
            keys_list.append(item.product_key)

        product_filter = Products.objects.filter(pk__in=keys_list).order_by('id')
        product = customizePagination(request, product_filter, 6)
        context = {"product": product}
    except:
        product = None
        context = {"product": product}

    return render(request, 'substitut/userproducts.html', context)


def search(request):
    """User's search return the result from query's form on index"""
    query = request.GET.get('query')
    nutriscore_number = {1: 'a',
                         2: 'b',
                         3: 'c',
                         4: 'd',
                         5: 'e'}

    if not query:
        product_list = Products.objects.all()
        product = customizePagination(request, product_list, 6)
        context = {"product": product}
    else:
        product_list = Products.objects.filter(name__icontains=query).order_by('nutriscore')

        if not product_list:
            search_one_product = requests.get("https://fr.openfoodfacts.org/cgi/search.pl?action=process&search_terms="
                                              + str(query) + "&sort_by=unique_scans_n&page_size=20&json=1")
            response = json.loads(search_one_product.text)
            products_created = 0
            for product_index in range(0, int(response['count'])):
                if response['products'][product_index]['states_hierarchy'][1] == 'en:complete':
                    try:
                        get_name = response['products'][product_index]['product_name']
                    except KeyError:
                        get_name = ''
                    try:
                        get_url = response['products'][product_index]['url']
                    except KeyError:
                        get_url = ''
                    try:
                        get_img = response['products'][product_index]['image_front_url']
                    except KeyError:
                        get_img = ''
                    try:
                        get_nutriscore = response['products'][product_index]['nutrition_grades']
                        for key, value in nutriscore_number.items():
                            if get_nutriscore == value:
                                get_nutriscore = key
                    except KeyError:
                        get_nutriscore = ''
                    try:
                        categories_tags = response['products'][product_index]['categories_hierarchy'][:]
                        listing_categories = []
                        for c in categories_tags:
                            cleaned_cat = c.split(':')
                            listing_categories.append(cleaned_cat[1])
                        get_cat = listing_categories
                    except KeyError:
                        get_cat = ''

                    Products.objects.create(name=get_name,
                                            nutriscore=get_nutriscore,
                                            category=get_cat,
                                            picture=get_img,
                                            url=get_url)
                    products_created += 1
                    if products_created < 30:
                        break


        filteringbycategory = Products.objects.filter(name__icontains=query)
        cat = []
        for i in filteringbycategory:
            cat.extend(i.category)
        cat = list(set(cat))

        try:
            product_list = Products.objects.filter(category__contained_by=cat) \
                .order_by('nutriscore', 'name')
            pc = []
            for p in filteringbycategory:
                pc.append(p.picture)
            product = customizePagination(request, product_list, 6)
            try:
                context = {"product": product,
                           "urlp": query,
                           "name": query,
                           "picture": pc[0]}
            except:
                context = {"product": product,
                           "urlp": query,
                           "name": query}
            print('Products.objects.filter(category__contained_by=cat)')
        except:
            product_list = Products.objects.filter(name__icontains=query) \
                .order_by('nutriscore', 'name')
            pc = []
            for p in filteringbycategory:
                pc.append(p.picture)
            product = customizePagination(request, product_list, 6)
            try:
                context = {"product": product,
                           "urlp": query,
                           "name": query,
                           "picture": pc[0]}
            except:
                context = {"product": product,
                           "urlp": query,
                           "name": query}
            print('Products.objects.filter(name__icontains=query)')

    return render(request, 'substitut/search.html', context)


def detail(request, product_id):
    """Details for a product"""
    try:
        product_detail = get_object_or_404(Products, pk=product_id)
        user = request.user.email
        saving = request.POST.get('saving')
        if saving:
            Saving.objects.create(contact=user,
                                  product_key=product_detail.pk)
            return  redirect('substitut:userproducts')

        print(product_detail.category)
        context = {'name': product_detail.name,
                   'nutriscore': product_detail.nutriscore,
                   'picture': product_detail.picture,
                   'url': product_detail.url}
    except:
        product_detail = get_object_or_404(Products, pk=product_id)
        context = {'name': product_detail.name,
                   'nutriscore': product_detail.nutriscore,
                   'picture': product_detail.picture,
                   'url': product_detail.url}

    return render(request, 'substitut/detail.html', context)

substitut/templates/substitut/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
  <title>Pur Beurre</title>
    {% load static %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'substitut/vendor/bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'substitut/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'substitut/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'substitut/css/creative.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
          <img src="{% static 'substitut/img/portfolio/fullsize/logo_pur_beurre.png' %}" class="img-fluid" alt="Responsive image" style="width: 5vh">
          Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          <div id="mynavformclass" class="form-control">
            <form action="{% url 'substitut:search' %}" method="get" accept-charset="utf-8">
              <input id="mynavform" class="form-control mr-sm-2" name="query" placeholder="Chercher" aria-label="Search">

                  </form>
            </form>
          </div>
          </li>
          <li class="nav-item">
              {% if user.is_authenticated %}
                 <a class="nav-link js-scroll-trigger" href="{% url 'substitut:useraccount' %}"><img src="{% static 'substitut/img/portfolio/thumbnails/noun_User_1214549.png' %}" class="img-fluid" alt="User by alvianwijaya from the Noun Project" style="width: 4vh"></a>
              {% else %}
                <a class="nav-link js-scroll-trigger" href="{% url 'substitut:login' %}"><img src="{% static 'substitut/img/portfolio/thumbnails/noun_User_1214549.png' %}" class="img-fluid" alt="User by alvianwijaya from the Noun Project" style="width: 4vh"></a>
              {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'substitut:userproducts' %}"><img src="{% static 'substitut/img/portfolio/thumbnails/noun_Carrot_29691%20copie.png' %}" class="img-fluid" alt="Carrot by Fabien Jouin from the Noun Project" style="width: 4vh"></a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link js-scroll-trigger" href="{% url 'substitut:logout' %}"><img src="{% static 'substitut/img/portfolio/thumbnails/noun_Power_652650.png' %}" class="img-fluid" alt="Power by Joris Millot from the Noun Project" style="width: 5vh"></a>
            {% else %}
                 <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'substitut:signup' %}">Créer un compte</a>
            {% endif %}
          </li>
          <!--<li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>-->
        </ul>
      </div>
    </div>
  </nav>

    {% block content %}{% endblock %}

    <!-- Contact -->
  <section id="bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Contactez-nous !</h2>
          <hr class="my-4">
          <p class="mb-5">Une question ? Une remarque ? N'hésitez pas à nous joindre par téléphone ou par mail :</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
          <p>000-000-000</p>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
          <p>
            <a href="mailto:your-email@your-domain.com">purbeurre@purbeurre.com</a>
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="fixed-bottom">
      <div class="fixed-bottom">
      <ul class="text-center list-unstyled list-inline">
          <li class="list-inline-item">
              <a href="{% url 'substitut:mentionslegales' %}">Mentions légales</a>
          </li>
          <li class="list-inline-item">
              <a href="#bg-dark">Contact</a>
          </li>
      </ul>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'substitut/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'substitut/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'substitut/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'substitut/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
  <script src="{% static 'substitut/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'substitut/js/creative.min.js' %}"></script>

</body>

</html>

substitut/templates/substitut/detail.html
{% extends 'substitut/base.html' %}
{% load static %}
{% block content %}
    <section id="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mx-auto text-center">

            <div class="col-lg-12" style="border-radius: 20px; height: 200px; background-image: url('{{ picture }}'); background-repeat: repeat-x; background-position: center;">
                <div class="row">
                    <div class="col-lg-6 mx-auto my-lg-5 rounded" style="background: #FFFFFF;">
                        <h2>Aliment : {{ name }}</h2>
                    </div>
                </div>
            </div>

        <div class="row">
            <div class="col-lg-6">
                 <ul class="list-unstyled">

                      {% if nutriscore == '1' %}
                        <img src="{% static 'substitut/img/a.svg' %}"  alt="Nutriscore A" style="height: 100px">
                     {% elif nutriscore == 'a'%}
                        <img src="{% static 'substitut/img/a.svg' %}"  alt="Nutriscore A" style="height: 100px">

                     {% elif nutriscore == '2'%}
                        <img src="{% static 'substitut/img/b.svg' %}"  alt="Nutriscore B" style="height: 100px">
                    {% elif nutriscore == 'b'%}
                        <img src="{% static 'substitut/img/b.svg' %}"  alt="Nutriscore B" style="height: 100px">

                     {% elif nutriscore == '3' %}
                        <img src="{% static 'substitut/img/c.svg' %}"  alt="Nutriscore C" style="height: 100px">
                    {% elif nutriscore == 'c' %}
                        <img src="{% static 'substitut/img/c.svg' %}"  alt="Nutriscore C" style="height: 100px">

                     {% elif nutriscore == '4'%}
                        <img src="{% static 'substitut/img/d.svg' %}"  alt="Nutriscore D" style="height: 100px">
                    {% elif nutriscore == 'd' %}
                        <img src="{% static 'substitut/img/d.svg' %}"  alt="Nutriscore D" style="height: 100px">

                     {% elif nutriscore == '5'%}
                        <img src="{% static 'substitut/img/e.svg' %}"  alt="Nutriscore E" style="height: 100px">
                      {% elif nutriscore == 'e'%}
                        <img src="{% static 'substitut/img/e.svg' %}"  alt="Nutriscore E" style="height: 100px">
                    {% else %}
                        <h2>{{ nutriscore|capfirst }}</h2>
                    {% endif %}
                 </ul>
            </div>

            <div class="col-lg-6">
                <ul class="list-unstyled">
                <li><h3>Repère nutritionnel pour 100g</h3></li>
                {% if user.is_authenticated %}
                    <li>
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" value="Enregistrer" name="saving" class="btn btn-success js-scroll-trigger">
                        </form>
                    </li>
                {% else %}
                    <li class="alert-info"> <h3>Pour enregistrer ce produit, <br><a href="{% url 'substitut:login' %}">connectez-vous !</a></h3></li>
                {% endif %}
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 mx-auto">
                <p>
                    <h4>
                        <a href="{{ url }}">voir la fiche sur Open Food Facts</a>
                    </h4>
                </p>
            </div>
        </div>

             <a class="btn btn-primary btn-xl js-scroll-trigger" href="/">Retour à l'acceuil du site</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

substitut/templates/substitut/form.html
{% if error %}
<p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
{% endif %}

{% if user.is_authenticated %}
Vous êtes connecté, {{ user.username }} !

{% else %}
<form method="post"  role="form" action="/">
{% csrf_token %}
    <div class="mx-auto col-lg-5">
    <ul class="list-unstyled text-center">
        <li><input type="text" class="form-control" name="username" placeholder="Nom d'utilisateur"></li>
        <li><input type="email" class="form-control" name="email" placeholder="Email"></li>
        <li><input type="password" class="form-control" name="password" placeholder="Mot de passe"></li>
    </ul>
    </div>
    <input type="submit" value="Me connecter" />
</form>
{% endif %}

substitut/templates/substitut/index.html
{% extends 'substitut/base.html' %}

{% block content %}
    <!-- Header -->
  <header class="masthead text-center text-white d-flex">

    <div id="welcomingcustomer" class="container my-auto col-lg-8">
      <div class="row">
        <div class="col-lg-12 mx-auto">
          <h1 class="text-center">
            <strong>Du gras, oui, mais de qualité !</strong>
          </h1>
        </div>
        <div class="col-lg-10 mx-auto">
          <h2 class="text-center">Trouvez un produit de substitution pour ceux que vous consommez tous les jours</h2>
            <div class="text-center">
                <form action="{% url 'substitut:search' %}" method="get" accept-charset="utf-8">
                    <div class="form-inline col-lg-12 mx-auto">
                        <input placeholder="Tapez le nom du produit" name="query" class="col-lg-8 col-sm-8 form-control">
                        <input type="submit" value="Chercher" class="btn btn-primary js-scroll-trigger col-lg-4 col-sm-4">
                    </div>
                  </form>
                <p></p>
            </div>
        </div>
      </div>
    </div>

  </header>

  <!-- History -->
  <section id="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Colette & Remy</h2>
          <hr class="my-4">
            <p>
                De la ratatouille aux croissants
                Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy,
                que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
            </p>

            <div class="row">
                <div class="col-lg-6">
                    <img class="img-fluid" src="../../static/substitut/img/portfolio/fullsize/colette-tatou-full%20(1).png" alt="Colette">
                </div>
                <div class="col-lg-6">
                    <img class="img-fluid" src="../../static/substitut/img/portfolio/fullsize/remy.png" alt="Remy">
                </div>
            </div>
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="#page-top">Je veux trouver un aliment !</a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

substitut/templates/substitut/login.html
{% extends 'substitut/base.html' %}


{% block content %}



<section id="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Vous connecter</h2>
          <hr class="my-4">


            <form method="post">
                {% csrf_token %}
                {%  include 'substitut/form.html' %}
            </form>
            <hr class="my-4">
            <div class="col-lg-6 mx-auto">
                {% if not user.is_authenticated %}
                <h4>Si vous n'avez pas de compte client, <a href="{% url 'substitut:signup' %}">cliquez ici</a>  pour en créer un !</h4>
                <hr class="my-4">
                {% endif %}
            </div>



          <a class="btn btn-primary btn-xl js-scroll-trigger" href="/">Retour à l'acceuil du site</a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

substitut/templates/substitut/logout.html
{% extends 'substitut/base.html' %}


{% block content %}



<section id="bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Vous êtes déconnecté</h2>
          <hr class="my-4">

            <p>Pour vous connecter, cliquez ici <a href="{% url 'substitut:login' %}">cliquez ici</a>.</p>



            <hr class="my-4">
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="/">Retour à l'acceuil du site</a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

substitut/templates/substitut/products.html
{% load static %}
<hr class="my-4">
                <div class="mx-auto">
                    {% if product %}
                        <ul class="list-inline">
                            {% for p in product %}

                                    <li class="list-inline-item">
                                        <p>
                                            {% if p.picture %}
                                                <img class="img-thumbnail" src="{{ p.picture }}" alt="product picture {{ p.name }}" style="max-height: 200px; max-width: 200px;">
                                            {% else %}
                                                <p style="border: solid 1px #17a2b8;">Image manquante</p>
                                            {% endif %}
                                            <h4>{{ p.name|truncatechars_html:15 }}</h4>


                                             {% if p.nutriscore == '1' %}
                                                <img src="{% static 'substitut/img/a.svg' %}"  alt="Nutriscore A" style="height: 100px">
                                             {% elif p.nutriscore == 'a'%}
                                                <img src="{% static 'substitut/img/a.svg' %}"  alt="Nutriscore A" style="height: 100px">

                                             {% elif p.nutriscore == '2'%}
                                                <img src="{% static 'substitut/img/b.svg' %}"  alt="Nutriscore B" style="height: 100px">
                                            {% elif p.nutriscore == 'b'%}
                                                <img src="{% static 'substitut/img/b.svg' %}"  alt="Nutriscore B" style="height: 100px">

                                             {% elif p.nutriscore == '3' %}
                                                <img src="{% static 'substitut/img/c.svg' %}"  alt="Nutriscore C" style="height: 100px">
                                            {% elif p.nutriscore == 'c' %}
                                                <img src="{% static 'substitut/img/c.svg' %}"  alt="Nutriscore C" style="height: 100px">

                                             {% elif p.nutriscore == '4'%}
                                                <img src="{% static 'substitut/img/d.svg' %}"  alt="Nutriscore D" style="height: 100px">
                                            {% elif p.nutriscore == 'd' %}
                                                <img src="{% static 'substitut/img/d.svg' %}"  alt="Nutriscore D" style="height: 100px">

                                             {% elif p.nutriscore == '5'%}
                                                <img src="{% static 'substitut/img/e.svg' %}"  alt="Nutriscore E" style="height: 100px">
                                              {% elif p.nutriscore == 'e'%}
                                                <img src="{% static 'substitut/img/e.svg' %}"  alt="Nutriscore E" style="height: 100px">
                                            {% else %}
                                                <h2>{{ p.nutriscore|capfirst }}</h2>
                                            {% endif %}

                                            <h4><a href="{% url 'substitut:detail' product_id=p.pk  %}">consulter</a></h4>

                                        {% if user.is_authenticated %}
                                                <form method="post" action="{% url 'substitut:detail' product_id=p.pk %}">
                                                    {% csrf_token %}
                                                    <i class="far fa-save fa-2x">
                                                    <input type="submit" value="sauvegarder" name="saving" class="btn btn-success js-scroll-trigger"></i>
                                                </form>
                                            {% endif %}
                                            </p>

                                        </li>

                                {% if forloop.counter|divisibleby:3 %}
                                    <div class="clearfix"></div>
                                {% endif %}


                            {% endfor %}
                        </ul>

                        <div class="clearfix"></div>
                          <nav aria-label="...">
                            <ul class="pager list-unstyled list-inline-item">
                              {% if product.has_previous %}
                                  <li class="list-inline-item"><a href="?query={{ urlp }}&page={{ product.previous_page_number }}">Précédent</a></li>
                              {% endif %}
                              {% if product.has_next %}
                                  <li class="list-inline-item"><a href="?query={{ urlp }}&page={{ product.next_page_number }}">Suivant</a></li>
                              {% endif %}
                            </ul>
                          </nav>

                        </div>


                        {% else %}
                        <div class="mx-auto col-lg-6 text-center">
                            <h3>Il n'y a pas de résultat correspondant à votre recherche</h3>
                        </div>

                    {% endif %}